# install.ps1 - PocketShell installer
# Generates <CmdName>.cmd (entry command), adds setup folder to CURRENT USER's PATH.
# Saved as UTF-8 with BOM so Windows PowerShell 5.1 reads Chinese correctly.
param([string]$CmdName = 'pocketshell')

# 命令名只允许字母/数字/下划线/连字符
if ($CmdName -notmatch '^[A-Za-z0-9_-]+$') {
    Write-Host '命令名只能包含字母/数字/下划线/连字符，请重试。' -ForegroundColor Red
    exit 1
}

$setupDir = (Split-Path -Parent $MyInvocation.MyCommand.Path).TrimEnd('\')
$cmdFile  = Join-Path $setupDir ($CmdName + '.cmd')

# 生成命令入口：指向上级目录的 pocketshell\__main__.py（不依赖目录名）
$content = @'
@echo off
rem PocketShell entry - generated by install.bat
setlocal
where python >nul 2>nul
if errorlevel 1 goto :py
python "%~dp0..\pocketshell\__main__.py" %*
goto :eof
:py
py "%~dp0..\pocketshell\__main__.py" %*
endlocal
'@
[System.IO.File]::WriteAllText($cmdFile, $content + "`r`n", (New-Object System.Text.ASCIIEncoding))

# 把 setup 目录加入用户 PATH（只改 HKCU，不动系统 PATH）
$p = [Environment]::GetEnvironmentVariable('Path', 'User')
if ($null -eq $p) { $p = '' }
$items = @($p -split ';' | Where-Object { $_ -ne '' })
if ($items -contains $setupDir) {
    Write-Host '[PocketShell] 目录已在用户 PATH 中，无需重复添加。'
} else {
    $items += $setupDir
    [Environment]::SetEnvironmentVariable('Path', ($items -join ';'), 'User')
    Write-Host ('[PocketShell] 已加入用户 PATH：' + $setupDir)
}
Write-Host ('命令入口已生成：' + $CmdName + '.cmd')
Write-Host ('请新开一个终端，然后输入 ' + $CmdName + ' 试试，例如：' + $CmdName + ' 查看当前目录')
